// Action Types
export const PUBLISH_ARTICLE = 'PUBLISH_ARTICLE';
export const PUBLISH_ARTICLE_SUCCESS = 'PUBLISH_ARTICLE_SUCCESS';
export const PUBLISH_ARTICLE_FAILURE = 'PUBLISH_ARTICLE_FAILURE';
export const PUBLISH_ARTICLE_REQUEST = 'PUBLISH_ARTICLE_REQUEST';
