export const COMMENT_SUCCESS = 'COMMENT_SUCCESS';
export const COMMENT_FAILURE = 'COMMENT_FAILURE';
export const COMMENT_POSTING = 'COMMENT_POSTING';
export const INITIALIZE_COMMENTS = 'INITIALIZE_COMMENTS';
export const COMMENT_ERROR_CLEARED = 'COMMENT_ERROR_CLEARED';
