
// follow user action types
export const FOLLOW_ACTION = 'FOLLOW_ACTION';
export const FOLLOW_ACTION_FAILURE = 'FOLLOW_ACTION_FAILURE';
export const FOLLOW__ACTION_SUCCESS = 'FOLLOW__ACTION_SUCCESS';
export const FOLLOW__ACTION_CLEAR = 'FOLLOW__ACTION_CLEAR';
export const GET_FOLLOWERS = 'GET_FOLLOWERS';
export const GET_FOLLOWERS_FAILURE = 'GET_FOLLOWERS_FAILURE';
export const GET_FOLLOWERS_SUCCESS = 'GET_FOLLOWERS_SUCCESS';
export const GET_FOLLOWING = 'GET_FOLLOWING';
export const GET_FOLLOWING_FAILURE = 'GET_FOLLOWING_FAILURE';
export const GET_FOLLOWING_SUCCESS = 'GET_FOLLOWING_SUCCESS';
