
// update user action types
export const GET_NOTIFICATION = 'GET_NOTIFICATION';
export const VIEW_NOTIFICATION = 'VIEW_NOTIFICATION';
export const VIEW_NOTIFICATION_FAILURE = 'VIEW_NOTIFICATION_FAILURE';
export const VIEW_NOTIFICATION_SUCCESS = 'VIEW_NOTIFICATION_SUCCESS';
export const CLEAR_NOTIFICATION = 'CLEAR_NOTIFICATION';
export const MARK__NOTIFICATION_AS_READ_SUCCESS = 'MARK__NOTIFICATION_AS_READ_SUCCESS';
export const MARK_NOTIFICATION_AS_READ = 'MARK_NOTIFICATION_AS_READ';
export const MARK_NOTIFICATION_AS_READ_FAILURE = 'MARK_NOTIFICATION_AS_READ_FALUIRE';
