export const REPLY_SUCCESS = 'REPLY_SUCCESS';
export const REPLY_FAILURE = 'REPLY_FAILURE';
export const REPLY_POSTING = 'REPLY_POSTING';
export const INITIALIZE_REPLY = 'INITIALIZE_REPLY';
export const REPLY_ERROR_CLEARED = 'REPLY_ERROR_CLEARED';
